### PR TITLE
Automatic pack namespace support

### PR DESCRIPTION
**Pull request by stevegeek**
As per discussion in #144 would be nice to support `automatic_pack_namespace`.

I tried to make a stab at this but think I've hit my limits for now. 

The changes here seem to produce the correct output with `pks list-definitions` but the test I added that uses the resolver ie failing... not sure why.

Also I don't know how best to implement the pack configuration parsing to actually parse out the configuration under a nested hash, ie `automatic_pack_namespace` is actually defined under `metadata` normally. At the moment I just added the `automatic_pack_namespace` boolean to the root of the `package.yml` so I could continue.

I also wasn't sure where to get the packs root path info from while determining the pack namespace name.

Finally I ran into an issue with wanting but go from a String value to a &String in a condition branch, but simply adding a & at the start of the expression resulted in errors about lifetimes of temporary values. So I added a `let` outside of the conditional but that just feels wrong!

Anyway the diff attached includes TODOs describing the above!

### CODE REVIEW

**Comment by stevegeek** [comment]
@alexevanczuk i know you guys are probably very busy so no pressure on this, but just wanted to reiterate that I think I can't take this any further myself as reached my Rustfu limits. If you prefer I can close the PR and maybe it can be revisited in future by someone else!

**Comment by alexevanczuk** [comment]
Ah hey, totally up to you. Feel free to close if you don't want to leave dangling PRs open – I can always pull the closed branch to base new work off of.

I was actually just thinking of this as I was using `automatic_pack_namespace` in my org's codebase and it was bothering me that `pks` wasn't picking it up automatically and needed the `packwerk.yml` change. I'll probably get to this at some point.

**Comment by stevegeek** [comment]
Ok thanks @alexevanczuk , happy to leave it open if you think you might pick it up in future!

**Comment by alexevanczuk** [comment]
Hey @stevegeek this is now implemented! https://github.com/alexevanczuk/packs/pull/214

let me know if it works for you!

**Comment by stevegeek** [comment]
@alexevanczuk Great thanks so much! Will try it out and let you know.

**Pull request closed without merging**
