### PR TITLE
Adding support for following symlinks

### PR DESCRIPTION
**Pull request by AndrewSwerlick**
The experimental AST based parser works great in mono-repos where the directory structure doesn't really cooperate with normal packwerk, like ours. The one issue we encountered was that our repository makes use of symlinks for a few things, and out of the box this fork does not follow symlinks. Fortunately it's a one line change to modify behavior. 

Would you be amenable to upstreaming this? Maybe behind a config flag?

### CODE REVIEW

**Review by alexevanczuk — COMMENTED** [review]
I think I'm down to merge this... to confirm, this should not affect apps that do not use symlinks right? And for apps that use symlinks, this change is invisible downstream of `walk_directory`? I.e. they just operate on files as if they weren't symlinked?

**Comment by AndrewSwerlick** [comment]
> I think I'm down to merge this... to confirm, this should not affect apps that do not use symlinks right? And for apps that use symlinks, this change is invisible downstream of `walk_directory`? I.e. they just operate on files as if they weren't symlinked?

That's right, the only change is to how `walkdir` walks the directory structure. It's worth noting that when `walkdir` encounters a symlink it will return the symlink path for the `.path` method, so that does affect how packs in the symlinked dirs get named, but that feels like reasonable behavior to me.

**Comment by AndrewSwerlick** [comment]
> It's worth noting that when `walkdir` encounters a file under a symlink the `.path` method for that file will return the absolute path going through the symlink, so that does affect how packs in the symlinked dirs get named, but that feels like reasonable behavior to me.

This behavior is documented here in `walkdir`'s documentation https://docs.rs/walkdir/latest/walkdir/struct.DirEntry.html#method.path

**Review by alexevanczuk — APPROVED** [review]
Sweet, let's ship it. Want to bump the patch version and push up? Then a new release will automatically be created once we merge on main and CI passes.

**Comment by AndrewSwerlick** [comment]
> Sweet, let's ship it. Want to bump the patch version and push up? Then a new release will automatically be created once we merge on main and CI passes.

Awesome, just bumped it, and cleaned up some lingering debug and whitespace changes. Thanks, excited to start using this.

**Comment by alexevanczuk** [comment]
Released here! https://github.com/alexevanczuk/packs/releases/tag/v0.1.79

Looking forward to hearing your feedback @AndrewSwerlick

**Pull request merged**
